/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.onlineshopping.product.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CartListProduct service. Represents a row in the &quot;Product_CartListProduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.onlineshopping.product.service.model.impl.CartListProductModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.onlineshopping.product.service.model.impl.CartListProductImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CartListProduct
 * @generated
 */
@ProviderType
public interface CartListProductModel extends BaseModel<CartListProduct> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cart list product model instance should use the {@link CartListProduct} interface instead.
	 */

	/**
	 * Returns the primary key of this cart list product.
	 *
	 * @return the primary key of this cart list product
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cart list product.
	 *
	 * @param primaryKey the primary key of this cart list product
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this cart list product.
	 *
	 * @return the ID of this cart list product
	 */
	public long getId();

	/**
	 * Sets the ID of this cart list product.
	 *
	 * @param id the ID of this cart list product
	 */
	public void setId(long id);

	/**
	 * Returns the cart list ID of this cart list product.
	 *
	 * @return the cart list ID of this cart list product
	 */
	public long getCartListId();

	/**
	 * Sets the cart list ID of this cart list product.
	 *
	 * @param cartListId the cart list ID of this cart list product
	 */
	public void setCartListId(long cartListId);

	/**
	 * Returns the product ID of this cart list product.
	 *
	 * @return the product ID of this cart list product
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this cart list product.
	 *
	 * @param productId the product ID of this cart list product
	 */
	public void setProductId(long productId);

	/**
	 * Returns the size of this cart list product.
	 *
	 * @return the size of this cart list product
	 */
	@AutoEscape
	public String getSize();

	/**
	 * Sets the size of this cart list product.
	 *
	 * @param size the size of this cart list product
	 */
	public void setSize(String size);

	/**
	 * Returns the quantity of this cart list product.
	 *
	 * @return the quantity of this cart list product
	 */
	public int getQuantity();

	/**
	 * Sets the quantity of this cart list product.
	 *
	 * @param quantity the quantity of this cart list product
	 */
	public void setQuantity(int quantity);

	/**
	 * Returns the create date of this cart list product.
	 *
	 * @return the create date of this cart list product
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this cart list product.
	 *
	 * @param createDate the create date of this cart list product
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cart list product.
	 *
	 * @return the modified date of this cart list product
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cart list product.
	 *
	 * @param modifiedDate the modified date of this cart list product
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CartListProduct cartListProduct);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CartListProduct> toCacheModel();

	@Override
	public CartListProduct toEscapedModel();

	@Override
	public CartListProduct toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}