/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.onlineshopping.product.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Image service. Represents a row in the &quot;Product_Image&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.onlineshopping.product.service.model.impl.ImageModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.onlineshopping.product.service.model.impl.ImageImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Image
 * @generated
 */
@ProviderType
public interface ImageModel extends BaseModel<Image> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a image model instance should use the {@link Image} interface instead.
	 */

	/**
	 * Returns the primary key of this image.
	 *
	 * @return the primary key of this image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this image.
	 *
	 * @param primaryKey the primary key of this image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this image.
	 *
	 * @return the uuid of this image
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this image.
	 *
	 * @param uuid the uuid of this image
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this image.
	 *
	 * @return the ID of this image
	 */
	public long getId();

	/**
	 * Sets the ID of this image.
	 *
	 * @param id the ID of this image
	 */
	public void setId(long id);

	/**
	 * Returns the view of this image.
	 *
	 * @return the view of this image
	 */
	@AutoEscape
	public String getView();

	/**
	 * Sets the view of this image.
	 *
	 * @param view the view of this image
	 */
	public void setView(String view);

	/**
	 * Returns the image url of this image.
	 *
	 * @return the image url of this image
	 */
	@AutoEscape
	public String getImageUrl();

	/**
	 * Sets the image url of this image.
	 *
	 * @param imageUrl the image url of this image
	 */
	public void setImageUrl(String imageUrl);

	/**
	 * Returns the product ID of this image.
	 *
	 * @return the product ID of this image
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this image.
	 *
	 * @param productId the product ID of this image
	 */
	public void setProductId(long productId);

	/**
	 * Returns the create date of this image.
	 *
	 * @return the create date of this image
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this image.
	 *
	 * @param createDate the create date of this image
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this image.
	 *
	 * @return the modified date of this image
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this image.
	 *
	 * @param modifiedDate the modified date of this image
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Image image);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Image> toCacheModel();

	@Override
	public Image toEscapedModel();

	@Override
	public Image toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}