/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.onlineshopping.product.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Wishlist service. Represents a row in the &quot;Product_Wishlist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.onlineshopping.product.service.model.impl.WishlistModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.onlineshopping.product.service.model.impl.WishlistImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Wishlist
 * @generated
 */
@ProviderType
public interface WishlistModel extends BaseModel<Wishlist> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wishlist model instance should use the {@link Wishlist} interface instead.
	 */

	/**
	 * Returns the primary key of this wishlist.
	 *
	 * @return the primary key of this wishlist
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wishlist.
	 *
	 * @param primaryKey the primary key of this wishlist
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this wishlist.
	 *
	 * @return the uuid of this wishlist
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this wishlist.
	 *
	 * @param uuid the uuid of this wishlist
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this wishlist.
	 *
	 * @return the ID of this wishlist
	 */
	public long getId();

	/**
	 * Sets the ID of this wishlist.
	 *
	 * @param id the ID of this wishlist
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this wishlist.
	 *
	 * @return the user ID of this wishlist
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this wishlist.
	 *
	 * @param userId the user ID of this wishlist
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this wishlist.
	 *
	 * @return the user uuid of this wishlist
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this wishlist.
	 *
	 * @param userUuid the user uuid of this wishlist
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this wishlist.
	 *
	 * @return the create date of this wishlist
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this wishlist.
	 *
	 * @param createDate the create date of this wishlist
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this wishlist.
	 *
	 * @return the modified date of this wishlist
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this wishlist.
	 *
	 * @param modifiedDate the modified date of this wishlist
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Wishlist wishlist);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Wishlist> toCacheModel();

	@Override
	public Wishlist toEscapedModel();

	@Override
	public Wishlist toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}