/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.onlineshopping.product.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringUtil;

import com.onlineshopping.product.service.model.CartListProduct;
import com.onlineshopping.product.service.model.CartListProductModel;
import com.onlineshopping.product.service.model.CartListProductSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CartListProduct service. Represents a row in the &quot;Product_CartListProduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CartListProductModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CartListProductImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CartListProductImpl
 * @generated
 */
@JSON(strict = true)
public class CartListProductModelImpl
	extends BaseModelImpl<CartListProduct> implements CartListProductModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cart list product model instance should use the <code>CartListProduct</code> interface instead.
	 */
	public static final String TABLE_NAME = "Product_CartListProduct";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"cartListId", Types.BIGINT},
		{"productId", Types.BIGINT}, {"size_", Types.VARCHAR},
		{"quantity", Types.INTEGER}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cartListId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("size_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("quantity", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Product_CartListProduct (id_ LONG not null primary key,cartListId LONG,productId LONG,size_ VARCHAR(75) null,quantity INTEGER,createDate DATE null,modifiedDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table Product_CartListProduct";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cartListProduct.cartListId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Product_CartListProduct.cartListId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.onlineshopping.product.service.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.onlineshopping.product.service.model.CartListProduct"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.onlineshopping.product.service.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.onlineshopping.product.service.model.CartListProduct"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.onlineshopping.product.service.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.onlineshopping.product.service.model.CartListProduct"),
		true);

	public static final long CARTLISTID_COLUMN_BITMASK = 1L;

	public static final long PRODUCTID_COLUMN_BITMASK = 2L;

	public static final long SIZE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CartListProduct toModel(CartListProductSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CartListProduct model = new CartListProductImpl();

		model.setId(soapModel.getId());
		model.setCartListId(soapModel.getCartListId());
		model.setProductId(soapModel.getProductId());
		model.setSize(soapModel.getSize());
		model.setQuantity(soapModel.getQuantity());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CartListProduct> toModels(
		CartListProductSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<CartListProduct> models = new ArrayList<CartListProduct>(
			soapModels.length);

		for (CartListProductSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.onlineshopping.product.service.service.util.ServiceProps.get(
			"lock.expiration.time.com.onlineshopping.product.service.model.CartListProduct"));

	public CartListProductModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CartListProduct.class;
	}

	@Override
	public String getModelClassName() {
		return CartListProduct.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CartListProduct, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CartListProduct, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CartListProduct, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CartListProduct)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CartListProduct, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CartListProduct, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CartListProduct)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CartListProduct, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CartListProduct, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CartListProduct>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CartListProduct.class.getClassLoader(), CartListProduct.class,
			ModelWrapper.class);

		try {
			Constructor<CartListProduct> constructor =
				(Constructor<CartListProduct>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CartListProduct, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CartListProduct, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CartListProduct, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<CartListProduct, Object>>();
		Map<String, BiConsumer<CartListProduct, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CartListProduct, ?>>();

		attributeGetterFunctions.put(
			"id",
			new Function<CartListProduct, Object>() {

				@Override
				public Object apply(CartListProduct cartListProduct) {
					return cartListProduct.getId();
				}

			});
		attributeSetterBiConsumers.put(
			"id",
			new BiConsumer<CartListProduct, Object>() {

				@Override
				public void accept(
					CartListProduct cartListProduct, Object idObject) {

					cartListProduct.setId((Long)idObject);
				}

			});
		attributeGetterFunctions.put(
			"cartListId",
			new Function<CartListProduct, Object>() {

				@Override
				public Object apply(CartListProduct cartListProduct) {
					return cartListProduct.getCartListId();
				}

			});
		attributeSetterBiConsumers.put(
			"cartListId",
			new BiConsumer<CartListProduct, Object>() {

				@Override
				public void accept(
					CartListProduct cartListProduct, Object cartListIdObject) {

					cartListProduct.setCartListId((Long)cartListIdObject);
				}

			});
		attributeGetterFunctions.put(
			"productId",
			new Function<CartListProduct, Object>() {

				@Override
				public Object apply(CartListProduct cartListProduct) {
					return cartListProduct.getProductId();
				}

			});
		attributeSetterBiConsumers.put(
			"productId",
			new BiConsumer<CartListProduct, Object>() {

				@Override
				public void accept(
					CartListProduct cartListProduct, Object productIdObject) {

					cartListProduct.setProductId((Long)productIdObject);
				}

			});
		attributeGetterFunctions.put(
			"size",
			new Function<CartListProduct, Object>() {

				@Override
				public Object apply(CartListProduct cartListProduct) {
					return cartListProduct.getSize();
				}

			});
		attributeSetterBiConsumers.put(
			"size",
			new BiConsumer<CartListProduct, Object>() {

				@Override
				public void accept(
					CartListProduct cartListProduct, Object sizeObject) {

					cartListProduct.setSize((String)sizeObject);
				}

			});
		attributeGetterFunctions.put(
			"quantity",
			new Function<CartListProduct, Object>() {

				@Override
				public Object apply(CartListProduct cartListProduct) {
					return cartListProduct.getQuantity();
				}

			});
		attributeSetterBiConsumers.put(
			"quantity",
			new BiConsumer<CartListProduct, Object>() {

				@Override
				public void accept(
					CartListProduct cartListProduct, Object quantityObject) {

					cartListProduct.setQuantity((Integer)quantityObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<CartListProduct, Object>() {

				@Override
				public Object apply(CartListProduct cartListProduct) {
					return cartListProduct.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<CartListProduct, Object>() {

				@Override
				public void accept(
					CartListProduct cartListProduct, Object createDateObject) {

					cartListProduct.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<CartListProduct, Object>() {

				@Override
				public Object apply(CartListProduct cartListProduct) {
					return cartListProduct.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<CartListProduct, Object>() {

				@Override
				public void accept(
					CartListProduct cartListProduct,
					Object modifiedDateObject) {

					cartListProduct.setModifiedDate((Date)modifiedDateObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getCartListId() {
		return _cartListId;
	}

	@Override
	public void setCartListId(long cartListId) {
		_columnBitmask = -1L;

		if (!_setOriginalCartListId) {
			_setOriginalCartListId = true;

			_originalCartListId = _cartListId;
		}

		_cartListId = cartListId;
	}

	public long getOriginalCartListId() {
		return _originalCartListId;
	}

	@JSON
	@Override
	public long getProductId() {
		return _productId;
	}

	@Override
	public void setProductId(long productId) {
		_columnBitmask |= PRODUCTID_COLUMN_BITMASK;

		if (!_setOriginalProductId) {
			_setOriginalProductId = true;

			_originalProductId = _productId;
		}

		_productId = productId;
	}

	public long getOriginalProductId() {
		return _originalProductId;
	}

	@JSON
	@Override
	public String getSize() {
		if (_size == null) {
			return "";
		}
		else {
			return _size;
		}
	}

	@Override
	public void setSize(String size) {
		_columnBitmask |= SIZE_COLUMN_BITMASK;

		if (_originalSize == null) {
			_originalSize = _size;
		}

		_size = size;
	}

	public String getOriginalSize() {
		return GetterUtil.getString(_originalSize);
	}

	@JSON
	@Override
	public int getQuantity() {
		return _quantity;
	}

	@Override
	public void setQuantity(int quantity) {
		_quantity = quantity;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CartListProduct.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CartListProduct toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CartListProduct>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CartListProductImpl cartListProductImpl = new CartListProductImpl();

		cartListProductImpl.setId(getId());
		cartListProductImpl.setCartListId(getCartListId());
		cartListProductImpl.setProductId(getProductId());
		cartListProductImpl.setSize(getSize());
		cartListProductImpl.setQuantity(getQuantity());
		cartListProductImpl.setCreateDate(getCreateDate());
		cartListProductImpl.setModifiedDate(getModifiedDate());

		cartListProductImpl.resetOriginalValues();

		return cartListProductImpl;
	}

	@Override
	public int compareTo(CartListProduct cartListProduct) {
		int value = 0;

		if (getCartListId() < cartListProduct.getCartListId()) {
			value = -1;
		}
		else if (getCartListId() > cartListProduct.getCartListId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CartListProduct)) {
			return false;
		}

		CartListProduct cartListProduct = (CartListProduct)object;

		long primaryKey = cartListProduct.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_originalCartListId = _cartListId;

		_setOriginalCartListId = false;

		_originalProductId = _productId;

		_setOriginalProductId = false;

		_originalSize = _size;

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CartListProduct> toCacheModel() {
		CartListProductCacheModel cartListProductCacheModel =
			new CartListProductCacheModel();

		cartListProductCacheModel.id = getId();

		cartListProductCacheModel.cartListId = getCartListId();

		cartListProductCacheModel.productId = getProductId();

		cartListProductCacheModel.size = getSize();

		String size = cartListProductCacheModel.size;

		if ((size != null) && (size.length() == 0)) {
			cartListProductCacheModel.size = null;
		}

		cartListProductCacheModel.quantity = getQuantity();

		Date createDate = getCreateDate();

		if (createDate != null) {
			cartListProductCacheModel.createDate = createDate.getTime();
		}
		else {
			cartListProductCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cartListProductCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cartListProductCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return cartListProductCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CartListProduct, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CartListProduct, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CartListProduct, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CartListProduct)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CartListProduct, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CartListProduct, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CartListProduct, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CartListProduct)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CartListProduct>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private long _cartListId;
	private long _originalCartListId;
	private boolean _setOriginalCartListId;
	private long _productId;
	private long _originalProductId;
	private boolean _setOriginalProductId;
	private String _size;
	private String _originalSize;
	private int _quantity;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private CartListProduct _escapedModel;

}