/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.onlineshopping.product.service.model.impl;

import com.onlineshopping.product.service.model.WishlistProduct;
import com.onlineshopping.product.service.service.WishlistProductLocalServiceUtil;

/**
 * The extended model base implementation for the WishlistProduct service. Represents a row in the &quot;Product_WishlistProduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WishlistProductImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WishlistProductImpl
 * @see WishlistProduct
 * @generated
 */
public abstract class WishlistProductBaseImpl
	extends WishlistProductModelImpl implements WishlistProduct {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a wishlist product model instance should use the <code>WishlistProduct</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			WishlistProductLocalServiceUtil.addWishlistProduct(this);
		}
		else {
			WishlistProductLocalServiceUtil.updateWishlistProduct(this);
		}
	}

}